#!/usr/bin/env bash

joinby() {
  local delim="$1"
  shift
  echo -n "$1"
  shift
  [[ -n $@ ]] && printf "${delim}%s" "$@"
}

keywords=(
README
bash_aliases
bash_comp
bashrc
gitconfig
githooks
inputrc
install
profile
tmux
vim
man
bin
todo
)

syntaxes=()
# Format: "keyword: Message."
any_keyword_regex="$(joinby '|' "${keywords[@]}")"
syntaxes+=("^$any_keyword_regex: [^[:lower:][:space:]].*[[:punct:]]$")
# Format: "Add ..."
syntaxes+=('^Add .*\.$')

syntax_verify_regex="$(joinby '|' "${syntaxes[@]}")"

if ! grep -qE "$syntax_verify_regex" "$1"; then
  >&2 echo "Invalid commit message. Aborting commit."
  exit 1
fi
