#!/usr/bin/env bash

if ! command -v stow &>/dev/null; then
  read -p 'Required tool stow is not installed. Install now? [Y/N] ' answer
  if [[ -z $answer || $answer =~ [yY](es)? ]]; then
    sudo apt install stow -y
  else
    >&2 echo 'Missing required tool stow. Aborted.'
    exit 1
  fi
fi

for package in */; do stow --target "$HOME" "$package" ; done
