[ -d ~/.gitconfig.d/ ] || exit

out="$HOME/.gitconfig.d/.load-extra-configs.gitconfig"

cat <<eof > "$out"
; Loads extra git configs: "~/.gitconfig.d/*.gitconfig".
;
; DO NOT EDIT. This file is automatically generated by your "~/.profile". Any
; *non-hidden* files matching "~/.gitconfig.d/*.gitconfig" will be included
; here.

[include]

eof

for f in ~/.gitconfig.d/*.gitconfig; do
  [ -r "$f" ] && echo "path = $f" >> "$out"
done
