#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  cat <<EOF
  Print tasks done in the last 7 days. NOTE: Archives the todo.txt.
    standup

EOF
  exit
}

>&2 chronic "$TODO_SH" archive
# - `$2 == "x"`: Done tasks are marked with an "x".
# - `$3` is the ISO date when the task was marked done.
"$TODO_SH" listall | awk -v start_date="$(date -d '7 day ago' -I)" '$2 == "x" && $3 >= start_date {print $0}'
